site_name: DermAlert
repo_url: https://github.com/DermAlert/dermalert.github.io
repo_name: DermAlert

nav:
  - Home: index.md

theme:
  name: material
  language: pt-BR
  favicon: assets/adaptive-icon.png
  logo: assets/adaptive-icon.png

  font:
    text: "Roboto"
    code: "Roboto Mono"

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: "#243447" 
      accent: "#243447"

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: "#243447" 
      accent: "#243447" 

extra_css:
  - stylesheets/extra.css
