site_name: DermAlert
repo_url: https://github.com/DermAlert/dermalert.github.io
repo_name: DermAlert

nav:
  - Home: index.md
  - Documentação técnica:
      - Frontend: documentacao-tecnica/frontend.md
      - Backend: documentacao-tecnica/backend.md
  - Código de Conduta: codigo-de-conduta.md
  - Documentação GCES: 
      - Equipe: documentacao-disciplina/equipe.md
      - Atas de Reunião: documentacao-disciplina/atas-reunioes.md
      - Backlog do projeto: documentacao-disciplina/backlog.md
      - Checklists: documentacao-disciplina/checklist.md
  - Guia de Contribuição: guia-de-contribuicao.md

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  language: pt-BR
  favicon: assets/adaptive-icon.png
  logo: assets/logo.png

  font:
    text: "Roboto"
    code: "Roboto Mono"

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: "#1A4568" 
      accent: "#1A4568"

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: "#1A4568" 
      accent: "#1A4568" 

extra_css:
  - stylesheets/extra.css
  - land/dist/assets/index-D5Lwlgl_.css

extra_javascript:
  - land/dist/assets/index-BMjkV8U-.js
